### ISSUE TITLE
TypeError 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Cyb0rg42** [fox-it/dissect#25]
I'm getting with every command the error: TtypeError 'type' object is not subscriptable. 
 In installed dissect with pip install dissect on a fully patch Ubuntu 20.04 LTS system with python 3.8.10

Any idea what can be wrong?

**Comment by Schamper** [comment]
Unfortunately dissect is not compatible with Python 3.8 and requires Python >= 3.9. Upgrading your Python version should fix this. Please note however that [a fix for Python 3.11](https://github.com/fox-it/dissect.target/pull/193) has not made it into the version on PyPI yet, so you're currently best off installing either Python 3.9 or Python 3.10. PyPy will also work great!

We added a minimum Python version of 3.9 to the package, but only after the initial release. Unfortunately the default behaviour of `pip` is to find the lowest version that it deems "compatible", which is the initial release without the minimum version requirement (but which still very much required >= 3.9). `pip` doesn't actually tell you it does this, though, which is annoying behaviour.

**Comment by Cyb0rg42** [comment]
Updated to python 3.9. Problem fixed😎
