### ISSUE TITLE
What about custom artifacts?

### ISSUE THREAD

**Issue by Flockenmumie** [fox-it/dissect#35]
Hi!
I really like acquire bc of the ease of dealing with images / vmdks.
Can you state what is the go-to way if I want to acquire my own artifacts? As far as I have seen, there is no option to provide a list of paths or similar. In this case, I will have to implement my own module, isn't it?
Thanks in advance for answering!

**Comment by Schamper** [comment]
Hi @Flockenmumie! You can easily acquire additional files or directories using the `--file`, `--dir` or `--glob` arguments. This is also shortly described in the documentation: https://docs.dissect.tools/en/latest/tools/acquire.html (last paragraph before the "Deployment" header).

If your acquisition requires some computation (i.e. needing to retrieve a path from the registry, or by parsing another file) then you need to implement your own module.
