### ISSUE TITLE
Dissect error during pytest

### ISSUE THREAD

**Issue by D3vil0p3r** [fox-it/dissect#69]
I get the following error during building from source:
```
==> Avvio di check() in corso...
/usr/lib/python3.12/site-packages/pytest_asyncio/plugin.py:208: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", "module", "package", "session"

  warnings.warn(PytestDeprecationWarning(_DEFAULT_FIXTURE_LOOP_SCOPE_UNSET))
===================================================================== test session starts ======================================================================
platform linux – Python 3.12.6, pytest-8.3.3, pluggy-1.5.0
rootdir: /tmp/makepkg/python-dissect/src/dissect
configfile: pyproject.toml
plugins: libtmux-0.37.0, requests-mock-1.11.0, anyio-4.4.0, flaky-3.8.1, cov-5.0.0, repeat-0.9.3, timeout-2.3.1, xdist-3.5.0, asyncio-0.24.0
asyncio: mode=Mode.STRICT, default_loop_scope=None
collected 0 items                                                                                                                                              

==================================================================== no tests ran in 0.02s =====================================================================
==> ERRORE: Si è verificato un errore in check().
    L'operazione sta per essere interrotta...
```

**Comment by Schamper** [comment]
What happens if you use `tox` to run the tests from a clean venv? At first glance this does not look like any error originating from our tests (we don't have any function called `check()` in the `dissect.target` codebase).

**Comment by D3vil0p3r** [comment]
> What happens if you use `tox` to run the tests from a clean venv? At first glance this does not look like any error originating from our tests (we don't have any function called `check()` in the `dissect.target` codebase).

I am packaging it for BlackArch (Arch-based) and it has a function that only run `pytest` command, nothing more. Even if I skip the tests and I actually install it, I see that library is not installed... I get only:
```
/usr/lib/python3.12/site-packages/dissect-3.16.1.dist-info/
```
but not a `/usr/lib/python3.12/site-packages/dissect`, so the lib seems to not installed correctly. In PKGBUILD I use the following commands for building and installing:
```
git -C dissect clean -dfx
cd dissect
python -m build --wheel --no-isolation
python -m installer dist/*.whl
```
Do you see something I'm missing?

**Comment by D3vil0p3r** [comment]
> It seems like you are trying to run `pytest` inside the `dissect` meta repository, which does not contain any tests.

Right. From the installation, should I expect to have `/usr/lib/python3.12/site-packages/dissect` dir?

**Comment by pyrco** [comment]
No, the `dissect` package currently does not have any files, it is just a bunch of dependencies. This means installing this package will not create a `.../site-packages/dissect` dir.

**Comment by D3vil0p3r** [comment]
Thank you very much. The reason of opening this issue was because when I tried to package dissect.archive, I got "No module 'dissect' found", so I thought this repository had a specific lib. I'm closing this issue and opening a specific on dissect.archive. Thanks again
